//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Uygulama.Droid.tr.edu.kku.ogrenciportal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StudentPortalSystemAndroidServiceSoap", Namespace="http://tempuri.org/")]
    public partial class StudentPortalSystemAndroidService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStudentInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentLogin2SystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentLecturesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentAutomationLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYemekhaneDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKutuphaneDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIstatistikDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebDuyuruOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebHaberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebEtkinlikOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StudentPortalSystemAndroidService() {
            this.Url = "https://********************************.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStudentInfoCompletedEventHandler GetStudentInfoCompleted;
        
        /// <remarks/>
        public event StudentLogin2SystemCompletedEventHandler StudentLogin2SystemCompleted;
        
        /// <remarks/>
        public event GetStudentLecturesCompletedEventHandler GetStudentLecturesCompleted;
        
        /// <remarks/>
        public event GetStudentAutomationLoginCompletedEventHandler GetStudentAutomationLoginCompleted;
        
        /// <remarks/>
        public event GetYemekhaneDetailsCompletedEventHandler GetYemekhaneDetailsCompleted;
        
        /// <remarks/>
        public event GetKutuphaneDataCompletedEventHandler GetKutuphaneDataCompleted;
        
        /// <remarks/>
        public event GetIstatistikDataCompletedEventHandler GetIstatistikDataCompleted;
        
        /// <remarks/>
        public event GetWebDuyuruCompletedEventHandler GetWebDuyuruCompleted;
        
        /// <remarks/>
        public event GetWebHaberCompletedEventHandler GetWebHaberCompleted;
        
        /// <remarks/>
        public event GetWebEtkinlikCompletedEventHandler GetWebEtkinlikCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStudentInfo(string StudentNo) {
            object[] results = this.Invoke("GetStudentInfo", new object[] {
                        StudentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentInfoAsync(string StudentNo) {
            this.GetStudentInfoAsync(StudentNo, null);
        }
        
        /// <remarks/>
        public void GetStudentInfoAsync(string StudentNo, object userState) {
            if ((this.GetStudentInfoOperationCompleted == null)) {
                this.GetStudentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentInfoOperationCompleted);
            }
            this.InvokeAsync("GetStudentInfo", new object[] {
                        StudentNo}, this.GetStudentInfoOperationCompleted, userState);
        }
        
        private void OnGetStudentInfoOperationCompleted(object arg) {
            if ((this.GetStudentInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentInfoCompleted(this, new GetStudentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentLogin2System", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StudentLogin2System(string StudentNo, string StudentPassword) {
            object[] results = this.Invoke("StudentLogin2System", new object[] {
                        StudentNo,
                        StudentPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StudentLogin2SystemAsync(string StudentNo, string StudentPassword) {
            this.StudentLogin2SystemAsync(StudentNo, StudentPassword, null);
        }
        
        /// <remarks/>
        public void StudentLogin2SystemAsync(string StudentNo, string StudentPassword, object userState) {
            if ((this.StudentLogin2SystemOperationCompleted == null)) {
                this.StudentLogin2SystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentLogin2SystemOperationCompleted);
            }
            this.InvokeAsync("StudentLogin2System", new object[] {
                        StudentNo,
                        StudentPassword}, this.StudentLogin2SystemOperationCompleted, userState);
        }
        
        private void OnStudentLogin2SystemOperationCompleted(object arg) {
            if ((this.StudentLogin2SystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentLogin2SystemCompleted(this, new StudentLogin2SystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentLectures", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KkuOgrenciAlinanDersler[] GetStudentLectures(string StudentNo) {
            object[] results = this.Invoke("GetStudentLectures", new object[] {
                        StudentNo});
            return ((KkuOgrenciAlinanDersler[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentLecturesAsync(string StudentNo) {
            this.GetStudentLecturesAsync(StudentNo, null);
        }
        
        /// <remarks/>
        public void GetStudentLecturesAsync(string StudentNo, object userState) {
            if ((this.GetStudentLecturesOperationCompleted == null)) {
                this.GetStudentLecturesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentLecturesOperationCompleted);
            }
            this.InvokeAsync("GetStudentLectures", new object[] {
                        StudentNo}, this.GetStudentLecturesOperationCompleted, userState);
        }
        
        private void OnGetStudentLecturesOperationCompleted(object arg) {
            if ((this.GetStudentLecturesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentLecturesCompleted(this, new GetStudentLecturesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentAutomationLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStudentAutomationLogin(string StudentNo) {
            object[] results = this.Invoke("GetStudentAutomationLogin", new object[] {
                        StudentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentAutomationLoginAsync(string StudentNo) {
            this.GetStudentAutomationLoginAsync(StudentNo, null);
        }
        
        /// <remarks/>
        public void GetStudentAutomationLoginAsync(string StudentNo, object userState) {
            if ((this.GetStudentAutomationLoginOperationCompleted == null)) {
                this.GetStudentAutomationLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentAutomationLoginOperationCompleted);
            }
            this.InvokeAsync("GetStudentAutomationLogin", new object[] {
                        StudentNo}, this.GetStudentAutomationLoginOperationCompleted, userState);
        }
        
        private void OnGetStudentAutomationLoginOperationCompleted(object arg) {
            if ((this.GetStudentAutomationLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentAutomationLoginCompleted(this, new GetStudentAutomationLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetYemekhaneDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetYemekhaneDetails(string StudentNo) {
            object[] results = this.Invoke("GetYemekhaneDetails", new object[] {
                        StudentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetYemekhaneDetailsAsync(string StudentNo) {
            this.GetYemekhaneDetailsAsync(StudentNo, null);
        }
        
        /// <remarks/>
        public void GetYemekhaneDetailsAsync(string StudentNo, object userState) {
            if ((this.GetYemekhaneDetailsOperationCompleted == null)) {
                this.GetYemekhaneDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYemekhaneDetailsOperationCompleted);
            }
            this.InvokeAsync("GetYemekhaneDetails", new object[] {
                        StudentNo}, this.GetYemekhaneDetailsOperationCompleted, userState);
        }
        
        private void OnGetYemekhaneDetailsOperationCompleted(object arg) {
            if ((this.GetYemekhaneDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYemekhaneDetailsCompleted(this, new GetYemekhaneDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKutuphaneData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKutuphaneData(string StudentNo) {
            object[] results = this.Invoke("GetKutuphaneData", new object[] {
                        StudentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKutuphaneDataAsync(string StudentNo) {
            this.GetKutuphaneDataAsync(StudentNo, null);
        }
        
        /// <remarks/>
        public void GetKutuphaneDataAsync(string StudentNo, object userState) {
            if ((this.GetKutuphaneDataOperationCompleted == null)) {
                this.GetKutuphaneDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKutuphaneDataOperationCompleted);
            }
            this.InvokeAsync("GetKutuphaneData", new object[] {
                        StudentNo}, this.GetKutuphaneDataOperationCompleted, userState);
        }
        
        private void OnGetKutuphaneDataOperationCompleted(object arg) {
            if ((this.GetKutuphaneDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKutuphaneDataCompleted(this, new GetKutuphaneDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIstatistikData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ToplamOgrenci[] GetIstatistikData() {
            object[] results = this.Invoke("GetIstatistikData", new object[0]);
            return ((ToplamOgrenci[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIstatistikDataAsync() {
            this.GetIstatistikDataAsync(null);
        }
        
        /// <remarks/>
        public void GetIstatistikDataAsync(object userState) {
            if ((this.GetIstatistikDataOperationCompleted == null)) {
                this.GetIstatistikDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIstatistikDataOperationCompleted);
            }
            this.InvokeAsync("GetIstatistikData", new object[0], this.GetIstatistikDataOperationCompleted, userState);
        }
        
        private void OnGetIstatistikDataOperationCompleted(object arg) {
            if ((this.GetIstatistikDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIstatistikDataCompleted(this, new GetIstatistikDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWebDuyuru", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DuyuruEtkinlikHaber[] GetWebDuyuru() {
            object[] results = this.Invoke("GetWebDuyuru", new object[0]);
            return ((DuyuruEtkinlikHaber[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWebDuyuruAsync() {
            this.GetWebDuyuruAsync(null);
        }
        
        /// <remarks/>
        public void GetWebDuyuruAsync(object userState) {
            if ((this.GetWebDuyuruOperationCompleted == null)) {
                this.GetWebDuyuruOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebDuyuruOperationCompleted);
            }
            this.InvokeAsync("GetWebDuyuru", new object[0], this.GetWebDuyuruOperationCompleted, userState);
        }
        
        private void OnGetWebDuyuruOperationCompleted(object arg) {
            if ((this.GetWebDuyuruCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebDuyuruCompleted(this, new GetWebDuyuruCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWebHaber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DuyuruEtkinlikHaber[] GetWebHaber() {
            object[] results = this.Invoke("GetWebHaber", new object[0]);
            return ((DuyuruEtkinlikHaber[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWebHaberAsync() {
            this.GetWebHaberAsync(null);
        }
        
        /// <remarks/>
        public void GetWebHaberAsync(object userState) {
            if ((this.GetWebHaberOperationCompleted == null)) {
                this.GetWebHaberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebHaberOperationCompleted);
            }
            this.InvokeAsync("GetWebHaber", new object[0], this.GetWebHaberOperationCompleted, userState);
        }
        
        private void OnGetWebHaberOperationCompleted(object arg) {
            if ((this.GetWebHaberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebHaberCompleted(this, new GetWebHaberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWebEtkinlik", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DuyuruEtkinlikHaber[] GetWebEtkinlik() {
            object[] results = this.Invoke("GetWebEtkinlik", new object[0]);
            return ((DuyuruEtkinlikHaber[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWebEtkinlikAsync() {
            this.GetWebEtkinlikAsync(null);
        }
        
        /// <remarks/>
        public void GetWebEtkinlikAsync(object userState) {
            if ((this.GetWebEtkinlikOperationCompleted == null)) {
                this.GetWebEtkinlikOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebEtkinlikOperationCompleted);
            }
            this.InvokeAsync("GetWebEtkinlik", new object[0], this.GetWebEtkinlikOperationCompleted, userState);
        }
        
        private void OnGetWebEtkinlikOperationCompleted(object arg) {
            if ((this.GetWebEtkinlikCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebEtkinlikCompleted(this, new GetWebEtkinlikCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KkuOgrenciAlinanDersler {
        
        private string dERS_KODUField;
        
        private string dERS_ADIField;
        
        private string oGR_GOR_ADField;
        
        private string oGR_GOR_SOYADField;
        
        /// <remarks/>
        public string DERS_KODU {
            get {
                return this.dERS_KODUField;
            }
            set {
                this.dERS_KODUField = value;
            }
        }
        
        /// <remarks/>
        public string DERS_ADI {
            get {
                return this.dERS_ADIField;
            }
            set {
                this.dERS_ADIField = value;
            }
        }
        
        /// <remarks/>
        public string OGR_GOR_AD {
            get {
                return this.oGR_GOR_ADField;
            }
            set {
                this.oGR_GOR_ADField = value;
            }
        }
        
        /// <remarks/>
        public string OGR_GOR_SOYAD {
            get {
                return this.oGR_GOR_SOYADField;
            }
            set {
                this.oGR_GOR_SOYADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DuyuruEtkinlikHaber {
        
        private string headerField;
        
        private string noField;
        
        /// <remarks/>
        public string Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ToplamOgrenci {
        
        private string myoBayanField;
        
        private string myoErkekField;
        
        private string lisansBayanField;
        
        private string lisansErkekField;
        
        private string ylBayanField;
        
        private string ylErkekField;
        
        private string doktoraBayanField;
        
        private string doktoraErkekField;
        
        /// <remarks/>
        public string myoBayan {
            get {
                return this.myoBayanField;
            }
            set {
                this.myoBayanField = value;
            }
        }
        
        /// <remarks/>
        public string myoErkek {
            get {
                return this.myoErkekField;
            }
            set {
                this.myoErkekField = value;
            }
        }
        
        /// <remarks/>
        public string lisansBayan {
            get {
                return this.lisansBayanField;
            }
            set {
                this.lisansBayanField = value;
            }
        }
        
        /// <remarks/>
        public string lisansErkek {
            get {
                return this.lisansErkekField;
            }
            set {
                this.lisansErkekField = value;
            }
        }
        
        /// <remarks/>
        public string ylBayan {
            get {
                return this.ylBayanField;
            }
            set {
                this.ylBayanField = value;
            }
        }
        
        /// <remarks/>
        public string ylErkek {
            get {
                return this.ylErkekField;
            }
            set {
                this.ylErkekField = value;
            }
        }
        
        /// <remarks/>
        public string doktoraBayan {
            get {
                return this.doktoraBayanField;
            }
            set {
                this.doktoraBayanField = value;
            }
        }
        
        /// <remarks/>
        public string doktoraErkek {
            get {
                return this.doktoraErkekField;
            }
            set {
                this.doktoraErkekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetStudentInfoCompletedEventHandler(object sender, GetStudentInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void StudentLogin2SystemCompletedEventHandler(object sender, StudentLogin2SystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentLogin2SystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentLogin2SystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetStudentLecturesCompletedEventHandler(object sender, GetStudentLecturesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentLecturesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentLecturesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KkuOgrenciAlinanDersler[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KkuOgrenciAlinanDersler[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetStudentAutomationLoginCompletedEventHandler(object sender, GetStudentAutomationLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentAutomationLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentAutomationLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetYemekhaneDetailsCompletedEventHandler(object sender, GetYemekhaneDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYemekhaneDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYemekhaneDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetKutuphaneDataCompletedEventHandler(object sender, GetKutuphaneDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKutuphaneDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKutuphaneDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetIstatistikDataCompletedEventHandler(object sender, GetIstatistikDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIstatistikDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIstatistikDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ToplamOgrenci[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ToplamOgrenci[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetWebDuyuruCompletedEventHandler(object sender, GetWebDuyuruCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebDuyuruCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebDuyuruCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DuyuruEtkinlikHaber[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DuyuruEtkinlikHaber[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetWebHaberCompletedEventHandler(object sender, GetWebHaberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebHaberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebHaberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DuyuruEtkinlikHaber[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DuyuruEtkinlikHaber[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetWebEtkinlikCompletedEventHandler(object sender, GetWebEtkinlikCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebEtkinlikCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebEtkinlikCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DuyuruEtkinlikHaber[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DuyuruEtkinlikHaber[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591